Integration tests for favourites  - debugin 403 error 2

diff --git a/.github/workflows/terrafrom_deploy_test_main.yml b/.github/workflows/terrafrom_deploy_test_main.yml
--- a/.github/workflows/terrafrom_deploy_test_main.yml
+++ b/.github/workflows/terrafrom_deploy_test_main.yml
@@ -120,43 +120,43 @@ jobs:
           python3 -m pytest tests/integration -v
         shell: bash
 
-  rollback:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: ${{ failure() }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
+#  rollback:
+#    runs-on: ubuntu-latest
+#    needs: deploy
+#    if: ${{ failure() }}
+#    steps:
+#      - name: Checkout repo
+#        uses: actions/checkout@v3
 
-      - name: Set up AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-region: ${{ env.TF_REGION }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#      - name: Set up AWS credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-region: ${{ env.TF_REGION }}
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v3
+#      - name: Set up Terraform
+#        uses: hashicorp/setup-terraform@v3
 
-      - name: Generate backend config
-        run: |
-          cat <<EOF > backend.conf.hcl 
-          bucket         = "${TF_BUCKET_NAME}"
-          key            = "${TF_BUCKET_KEY}"
-          region         = "${TF_REGION}"
-          dynamodb_table = "${TF_DYNAMO_TABLE}"
-          encrypt        = true
-          EOF
+#      - name: Generate backend config
+#        run: |
+#          cat <<EOF > backend.conf.hcl 
+#          bucket         = "${TF_BUCKET_NAME}"
+#          key            = "${TF_BUCKET_KEY}"
+#          region         = "${TF_REGION}"
+#          dynamodb_table = "${TF_DYNAMO_TABLE}"
+#          encrypt        = true
+#          EOF
 
-      - name: Terraform Init
-        run: terraform init -backend-config=backend.conf.hcl 
-        working-directory: .
+#      - name: Terraform Init
+#        run: terraform init -backend-config=backend.conf.hcl 
+#        working-directory: .
 
-      - name: Rollback - Terraform Destroy
-        run: terraform destroy -auto-approve
-        working-directory: .
+#      - name: Rollback - Terraform Destroy
+#        run: terraform destroy -auto-approve
+#        working-directory: .
 
-      - name: Rollback - Delete Lambda ZIPs from S3
-        run: |
-          aws s3 rm s3://$S3_BUCKET/authorizer_function.zip || true
-          aws s3 rm s3://$S3_BUCKET/userfunction.zip || true
+#      - name: Rollback - Delete Lambda ZIPs from S3
+#        run: |
+#          aws s3 rm s3://$S3_BUCKET/authorizer_function.zip || true
+#          aws s3 rm s3://$S3_BUCKET/userfunction.zip || true
